
version: '3.3'

services:
  web-server:
    container_name: 'api_mysql'
    build: .
    volumes:
    - .:/app
    - node_modules:/app/node_modules
    ports:
      - 3031:3030
    stdin_open: true
    environment:
      - PORT=3031
    command: npm run dev
  mysql:
    container_name: database
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: 172.17.0.1
      MYSQL_PORT: 3031
      MYSQL_USER: mysql
      MYSQL_PASSWORD: fernanda123
      MYSQL_DBNAME: apigethired
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
    - 8081:8080

volumes:
  node_modules: